const WordList = {
  sfa: ["twiggy", "sfasu", "sawdust", "homecoming", "phipsi", "pinelog", "stonefort", "purple", "jacks"],
  compSci: ["byte", "pixel", "code", "array", "queue", "stack", "index", "input", "output", "regex", "class", "method", "cache", "node", "debug"],
  animals: ["tiger", "panda", "gecko", "koala", "otter", "horse", "zebra", "sloth", "rhino", "bison", "lemur", "ferret", "skunk", "falcon"],
  misc: ["cake", "bird", "tree", "play", "frog", "book", "rain", "fish", "game", "ship", "apple", "beach", "chair", "dance", "eagle", "fancy", "glass", "happy", "igloo", "jelly", "banana", "dancer", "eleven", "falcon", "guitar", "hammer", "jacket", "killer", "laptop", "zebra", "garden", "moon", "robot", "sunset", "dragon", "island", "ninja", "octopus", "parrot", "quasar", "violet", "whale", "yacht", "zephyr", "acoustic", "blossom", "cascade", "eclipse", "flamingo", "galaxy", "lullaby", "monsoon", "candy", "blaze", "apple", "ghost", "happy", "magic", "music", "ocean", "piano", "queen", "river", "smile", "train", "umbra", "zebra", "fairy", "jelly", "lucky", "noble", "snail"],
  all: ["twiggy", "sfasu", "sawdust", "homecoming", "phipsi", "pinelog", "stonefort", "purple", "jacks", "byte", "pixel", "code", "array", "queue", "stack", "index", "input", "output", "regex", "class", "method", "cache", "node", "debug", "tiger", "panda", "gecko", "koala", "otter", "horse", "zebra", "sloth", "rhino", "bison", "lemur", "ferret", "skunk", "falcon", "cake", "bird", "tree", "play", "frog", "book", "rain", "fish", "game", "ship", "apple", "beach", "chair", "dance", "eagle", "fancy", "glass", "happy", "igloo", "jelly", "banana", "dancer", "eleven", "falcon", "guitar", "hammer", "jacket", "killer", "laptop", "zebra", "garden", "moon", "robot", "sunset", "dragon", "island", "ninja", "octopus", "parrot", "quasar", "violet", "whale", "yacht", "zephyr", "acoustic", "blossom", "cascade", "eclipse", "flamingo", "galaxy", "lullaby", "monsoon", "candy", "blaze", "apple", "ghost", "happy", "magic", "music", "ocean", "piano", "queen", "river", "smile", "train", "umbra", "zebra", "fairy", "jelly", "lucky", "noble", "snail"]
};

module.exports = WordList;
